name: Android Emulator Appium Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel
          emulator-options: -no-window -no-audio -no-boot-anim
          script: echo "Emulator started"

      - name: Install Appium
        run: |
          npm install -g appium@2.0.0
          appium driver install uiautomator2

      - name: Start Appium server
        run: |
          nohup appium --base-path /wd/hub > appium.log 2>&1 &
          sleep 10

      - name: Grant permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: app/build/reports/tests/test/

